[core]
name: vpe_builder
class: CustomUnitMetadata
overrideAndReplace: builder

displayLocaleKey: builder
displayDescription: -Constructs and repairs buildings.\n-Can refit into a Combat Engineer after building 2 Extractors.

price: 500
maxHp: 170
mass: 3000

techLevel: 1
buildSpeed: 0.002
availableInDemo: false

radius: 10
displayRadius: 12

isBio: false
isBuilder: true

canRepairBuildings: true
canRepairUnits: false
canReclaimResources: true

nanoRange: 95
nanoBuildSpeed: 1
nanoRepairSpeed: 0.3

transportSlotsNeeded: 1

canBuild_1_name: reclaim
canBuild_1_pos: -1

canBuild_2_name: extractor
canBuild_2_pos: 3

canBuild_3_name: landFactory
canBuild_3_pos: 4

canBuild_4_name: mechFactory
canBuild_4_pos: 4.1

canBuild_5_name: airFactory
canBuild_5_pos: 5

canBuild_6_name: seaFactory
canBuild_6_pos: 6

canBuild_7_name: fabricator
canBuild_7_pos: 7

canBuild_8_name: repairBay
canBuild_8_pos: 8

canBuild_9_name: turret
canBuild_9_pos: 3.1

canBuild_10_name: antiAirTurret
canBuild_10_pos: 3.2

canBuild_11_name: laserDefence
canBuild_11_pos: 12

canBuild_12_name: experimentalLandFactory
canBuild_12_pos: 13

canBuild_13_name: antiNukeLaucher
canBuild_13_pos: 14

[action_refitCombatEngineer]
convertTo: combatEngineer
price: 3500
text: Refit to Combat Engineer
description: Converts this Builder into a standard Combat Engineer. Requires 2 Extractors.
descriptionAddUnitStats: combatEngineer
unitShownInUI: combatEngineer
displayType: upgrade
buildSpeed: 33.3s
whenBuilding_cannotMove: true
isLocked: if numberOfUnitsInTeam(withTag='vpe_extractor', lessThan=2)
isLockedMessage: Requires 2 Extractors
isLockedAlt: if self.isMoving()
isLockedAltMessage: Stop moving to refit
pos: 0.2
iconExtraImage: SHARED:icon_upgrade_top.png
iconExtraColor: #AAFFFFFF

[graphics]
total_frames: 1
image: builder.png
image_wreak: builder_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[turret_1]
# Nano turret must be slot 1 for builder behavior.
x: 0
y: 5
invisible: true
warmup:30

canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.08

maxTurnSpeed: 1.7
turnAcceleration: 0.25

moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: true
